# Generated by Django 4.0.1 on 2023-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desctiption',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
